title: Francis Partron Addo


logo: 1.jpg


show_downloads: true


theme: jekyll-theme-minimal


include:
  - assets/css/style.css


description: >-
  Data Analyst | BI Analyst | Passionate about Workflow Automation & Sustainability.





